[tool.poetry]
name = "database-companies-and-vacancies-hh"
version = "0.1.0"
description = ""
authors = ["Yulia Samoylova <u.u.samoylova@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.3"
psycopg2 = "^2.9.10"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pandas = "^2.2.3"
google-api-python-client = "^2.162.0"


[tool.poetry.group.lint.dependencies]
black = "^25.1.0"
mypy = "^1.15.0"
isort = "^6.0.0"
flake8 = "^7.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | dist
  )/
  | foo.py
)
'''

[tool.isort]
line_length = 119

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
exclude = 'venv'
